src/backend/backend_web/memory.rs
Hi! Great work on this – I spotted this typo in a `Reflect::set` call while reading through to familiarize myself with the library and thought I'd send a PR. Tests ran and passed with `cargo test -F backend_wasmi` on an M2 Mac. Thanks for taking a look!
=> fix: correct {"intial"->"initial"} in Reflect call in memory.rs

src/backend/backend_wasmi.rs, src/backend/backend_wasmtime.rs, src/backend/backend_web/mod.rs, src/backend/mod.rs, src/lib.rs
Re #5 
I wanted to see what a cleaned-up `ExternRef` API could look like. In this design, I've chosen to mirror the `wasmtime` API more, i.e. `None` is external to `ExternRef`.
I also noticed that the current API provides access to the inner data with the lifetime of the store, not the `ExternRef` borrow, which is implemented for the `wasmtime` wrapper in a way that has exploded my brain (somehow we go from a `'self` lifetime to an `'a` lifetime even though they are in no way related, and all by the downcast_ref to an `Option<&'self &Option>` [note that Rust does not allow writing this as `Option<&'self &'a Option>` since we have not guaranteed that `'a: 'self`] - does this ever succeed?). Only exposing the borrowed lifetime seems an easier choice that provides more flexibility to …
=> Sketch cleaned-up ExternRef API

Cargo.toml, backends/js_wasm_runtime_layer/Cargo.toml, backends/js_wasm_runtime_layer/src/module.rs, backends/wasmtime_runtime_layer/Cargo.toml, backends/wasmtime_runtime_layer/src/lib.rs
This PR upgrades `wasmtime` to v19, which includes its migration to a separate `Ref` type. Since the `wasm_runtime_layer` still inlines all ref types in the `Value`, the asserts that `wasmtime` previously had against creating e.g. a table of type `i32` are now pushed up into the `wasm_runtime_layer`.
This PR also upgrades the `wasmparser` dependency for the `js_wasm_runtime_layer` but doesn't bump its version - this could be done if wanted or once more changes have been made to that backend.
=> Upgrade `wasmtime_runtime_layer` to v19

Cargo.toml, backends/wasmtime_runtime_layer/Cargo.toml, backends/wasmtime_runtime_layer/src/lib.rs
~~Blocked on #10~~
This PR upgrades `wasmtime` to v20, which includes its usage of `Rooted` GC reference types. It also introduces a new anyref type, which `wasm_runtime_layer` does not support.
=> Upgrade `wasmtime_runtime_layer` to v20

Cargo.toml, backends/js_wasm_runtime_layer/Cargo.toml, backends/wasmi_runtime_layer/Cargo.toml, backends/wasmi_runtime_layer/src/lib.rs, backends/wasmtime_runtime_layer/Cargo.toml
This PR upgrades `wasmtime` to v22 and `wasmi` to v32 and bumps their runtime crates to the matching versions.
The `wasmtime` update is without changes, `wasmi` needed some minor fixes.
=> Upgrade wasmtime to 22.0.0 and wasmi to 0.32.0

Cargo.toml, backends/wasmi_runtime_layer/Cargo.toml
PR 2/3, this one contains version bumps for
- wasmi 0.34
Blocked on #15
=> Bump wasmi backend to 0.34

Cargo.toml, backends/wasmi_runtime_layer/Cargo.toml
PR 3/3, this one contains version bumps for
- wasmi 0.35
Blocked on #16
=> Bump wasmi backend on 0.35

Cargo.toml, backends/wasmi_runtime_layer/Cargo.toml
PR 4/3, this one contains version bumps for
- wasmi 0.36
Blocked on #17
=> Bump wasmi backend on 0.36

Cargo.toml, backends/js_wasm_runtime_layer/Cargo.toml, backends/wasmtime_runtime_layer/Cargo.toml, backends/wasmtime_runtime_layer/src/lib.rs, src/backend.rs, src/lib.rs
This is the regular version bump for `wasmtime_runtime_layer` to v24
This PR includes a small required change to the `wasm_runtime_layer` crate, which results in a minor version bump to 0.4.2: the `Value` (and `backend::Value`) types get a new `ty(&self) -> ValueType` method. This method is required to use `wasmtime` v24 without introducing an unnecessary panic path.
=> Upgrade wasmtime-runtime-layer to v24

Cargo.toml, backends/js_wasm_runtime_layer/Cargo.toml, backends/wasmi_runtime_layer/Cargo.toml
This PR includes the version bump for wasmi, which requires no implementation changes, and some minor workspace cleanup.
The new version 0.37.0 for `wasmi_runtime_layer` should be released after merging this PR
=> Bump wasmi_runtime_layer to v0.37

Cargo.toml, backends/js_wasm_runtime_layer/Cargo.toml, backends/js_wasm_runtime_layer/src/module.rs, backends/wasmtime_runtime_layer/Cargo.toml, backends/wasmtime_runtime_layer/src/lib.rs
This time there are API changes in wasmtime v26: it now supports table64 by default, so we to convert between `u64` and `u32` for table sizes
Also, in my continuous effort to keep the `js_wasmtime_runtime_layer` dependencies up-to-date, `wasmparser::Payload` is now non-exhaustive and I thought it would look silly to have so many no-op cases *and* a catch-all, so I combined them.
=> Upgrade wasmtime_runtime_layer to v26.0

Cargo.toml, backends/js_wasm_runtime_layer/Cargo.toml, backends/wasmtime_runtime_layer/Cargo.toml, backends/wasmtime_runtime_layer/src/lib.rs
There are just two noteworthy changes in this PR:
- downcasting externrefs now needs to check that they're not anyrefs
- running wasmtime tests now requires enabling one gc implementation feature - since we don't want to choose for users, we only enable it in our tests but not in the wasmtime-runtime-layer crate itself
=> Bump wasmtime to v27

Cargo.toml, backends/js_wasm_runtime_layer/Cargo.toml, backends/js_wasm_runtime_layer/src/func.rs, backends/js_wasm_runtime_layer/src/instance.rs, backends/js_wasm_runtime_layer/src/lib.rs, backends/js_wasm_runtime_layer/src/module.rs, backends/js_wasm_runtime_layer/src/store.rs, backends/js_wasm_runtime_layer/src/table.rs, backends/wasmi_runtime_layer/Cargo.toml, backends/wasmi_runtime_layer/src/lib.rs, backends/wasmtime_runtime_layer/Cargo.toml, backends/wasmtime_runtime_layer/src/lib.rs, src/backend.rs, src/lib.rs, tests/add_one.rs, tests/multi_value.rs
Re #36
This PR upgrades all crates to be almost no-std. Unfortunately, `wasm_runtime_layer` cannot be fully no-std yet, since `std::io::Read` is std-only (see https://github.com/rust-lang/rust/issues/48331), which is used in `Module::new`.
This PR could be merged as a step in the right direction, with the hope that we might be able to be fully no-std once `std::io::Read` lives in `alloc`. Alternatively, we could make a breaking change to the API to not rely on `std::io::Read`.
=> Add `std` feature to all crates for no-std support

Cargo.toml, backends/js_wasm_runtime_layer/Cargo.toml, backends/wasmi_runtime_layer/Cargo.toml, backends/wasmi_runtime_layer/src/lib.rs, backends/wasmtime_runtime_layer/src/lib.rs
wasmi 0.41 adds support for memory64 and table64, so I've reused our approach from wasmtime to restrict support to 32bit only
=> Upgrade wasmi_runtime_layer to v0.41

.github/workflows/ci.yml, Cargo.toml, README.md, backends/js_wasm_runtime_layer/src/lib.rs, backends/js_wasm_runtime_layer/src/memory.rs, backends/wasmer_runtime_layer/Cargo.toml, backends/wasmer_runtime_layer/README.md, backends/wasmer_runtime_layer/src/lib.rs, backends/wasmtime_runtime_layer/Cargo.toml, backends/wasmtime_runtime_layer/src/lib.rs, tests/add_one.rs, tests/multi_value.rs
Fixes #34 
Adds a backend implementation using `wasmer`. At the moment, only `wasmer`'s `sys` backend is supported.
@tliron What are your thoughts?
=> Add a `wasmer_runtime_layer` backend

Cargo.toml, backends/wasmi_runtime_layer/Cargo.toml
Just a version bump, depends on #41 being merged
=> Bump wasmi_runtime_layer to v0.42

Cargo.toml, backends/js_wasm_runtime_layer/Cargo.toml, backends/js_wasm_runtime_layer/src/func.rs, backends/js_wasm_runtime_layer/src/lib.rs, backends/js_wasm_runtime_layer/src/store.rs, backends/wasmer_runtime_layer/src/lib.rs, backends/wasmi_runtime_layer/src/lib.rs, backends/wasmtime_runtime_layer/Cargo.toml, backends/wasmtime_runtime_layer/src/lib.rs, src/backend.rs, src/lib.rs
With https://github.com/bytecodealliance/wasmtime/pull/10760, wasmtime now requires `T: 'static` for store. While we advocated to not have the bound in wasmi, it now seems like the ship has sailed and we have to adapt.
@alexcrichton Since you also tried to avoid a static bound for as long as possible, do you think it makes sense for our abstraction over several WASM runtimes to adopt the bound?
@Robbepop If we go forward here, it means you can bring back the static bound in wasmi as well - thank you for removing it a few versions ago to help our downstream crate, now the momentum is in favour of your original change.
@DouglasDwyer This will require a major release for wasm_runtime_layer (and wasm_component_layer). I've prepared updates for wasmtime_runtime_layer and js_wasm_runtime_layer …
=> Require T: 'static for Store, upgrade to wasmtime_runtime_layer v34.0.0

.github/workflows/ci.yml, Cargo.toml, backends/js_wasm_runtime_layer/Cargo.toml, backends/js_wasm_runtime_layer/src/conversion.rs, backends/js_wasm_runtime_layer/src/lib.rs, backends/js_wasm_runtime_layer/src/store.rs, backends/wasmer_runtime_layer/src/lib.rs, backends/wasmi_runtime_layer/Cargo.toml, backends/wasmi_runtime_layer/src/lib.rs, backends/wasmtime_runtime_layer/src/lib.rs, src/backend.rs, src/lib.rs, tests/add_one.rs, tests/multi_value.rs
- upgrades `wasmi_runtime_layer` to v0.49
- resolves some new lints from Rust 1.89
- removes some dead code from the `js_wasm_runtime_layer`
=> Bump wasmi_runtime_layer to v0.49

Cargo.toml, backends/wasmtime_runtime_layer/Cargo.toml, backends/wasmtime_runtime_layer/src/lib.rs
Mostly a version bump but also adds a match case for wasmtime's newly added exception reference support
=> Bump wasmtime_runtime_layer to v36.0

Cargo.toml, backends/wasmtime_runtime_layer/Cargo.toml, backends/wasmtime_runtime_layer/src/lib.rs
Mostly a version bump but also adds a match case for wasmtime's newly added continuation reference support
=> Bump wasmtime_runtime_layer to v37.0
